apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app: docker-ssh
 name: docker-ssh
spec:
 replicas: 1
 selector:
  matchLabels:
   app: docker-ssh
 template:
  metadata:
   labels:
    app: docker-ssh
  spec:
   containers:
   - image: chrisley75/docker-ssh:0.0.1
     name: docker-ssh
     ports:
     - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
 name: lb-svc
 labels:
  app: lb-svc
spec:
 type: LoadBalancer
 selector:
   app: docker-ssh
 ports:
 - port: 2222
   targetPort: 22
   name: ssh
   protocol: TCP
